import json
import uuid
from typing import Any, List

import mmh3
import numpy as np
from pydantic import BaseModel, Field
from typing_extensions import Annotated


class Document:
    id: str
    content: str
    content_type: str = ("text",)  # type: ignore
    dataframe: str | None = None
    keywords: list[str] | None = None
    meta: dict[str, Any] = (None,)  # type: ignore
    score: float | None = None
    embedding: np.ndarray | None = None
    id_hash_keys: list[str] | None = None

    def __init__(
        self,
        content: str,
        content_type: str = "text",
        dataframe: str | None = None,
        keywords: list[str] | None = None,
        id: str | None = None,
        score: float | None = None,
        meta: dict[str, Any] | None = None,
        embedding: np.ndarray | None = None,
        id_hash_keys: list[str] | None = None,
        force_unique_id: bool = False,
        chunk_type: str = "Paragraph",
    ):
        """
        One of the core data classes in jaiai. It's used to represent documents / passages in a standardized way.
        Documents are stored in DocumentStores, are returned by Retrievers, are the input for Readers and are used in
        many other places that manipulate or interact with document-level data.
        Note: There can be multiple Documents originating from one file (e.g. PDF), if you split the text
        into smaller passages. We'll have one Document per passage in this case.
        Each document has a unique ID. This can be supplied by the user or generated automatically.
        It's particularly helpful for handling of duplicates and referencing documents in other objects (e.g. Labels)
        There's an easy option to convert from/to dicts via `from_dict()` and `to_dict`.
        :param content: Content of the document. For most cases, this will be text, but it can be a table or image.
        :param content_type: One of "text", "image_description". We can use this for handling of Documents and check compatibility.
        :param id: Unique ID for the document. If not supplied by the user, we'll generate one automatically by
                   creating a hash from the supplied text. This behaviour can be further adjusted by `id_hash_keys`.
        :param score: The relevance score of the Document determined by a model (e.g. Retriever or Re-Ranker).
                      If model's `scale_score` was set to True (default) score is in the unit interval (range of [0,1]), where 1 means extremely relevant.
        :param meta: Meta fields for a document like name, url, or author in the form of a custom dict (any keys and values allowed).
        :param embedding: Vector encoding of the text
        :param id_hash_keys: Generate the document id from a custom list of strings that refere to the documents attributes.
                             If you want ensure you don't have duplicate documents in your DocumentStore but texts are
                             not unique, you can modify the metadata and pass e.g. "meta" to this field (e.g. ["content", "meta"]).
                             In this case the id will be generated by using the content and the defined metadata.
        :param force_unique_id: Whether we need to perform unique random hash generation or generate it conditioning on fields
        """  # noqa: E501

        if content is None:
            raise ValueError("Can't create 'Document': Mandatory 'content' field is None")

        self.content = content
        self.content_type = content_type
        self.dataframe = dataframe
        self.keywords = keywords
        self.score = score
        self.meta = meta or {}

        allowed_hash_key_attributes = [
            "content",
            "content_type",
            "dataframe",
            "keywords",
            "score",
            "meta",
            "embedding",
        ]

        if id_hash_keys is not None:  # noqa: SIM102
            if not set(id_hash_keys) <= set(allowed_hash_key_attributes):  # type: ignore
                raise ValueError(
                    f"You passed custom strings {id_hash_keys} to id_hash_keys which is deprecated. Supply instead a list"
                    f" of Document's attribute names that the id should be based on (e.g. {allowed_hash_key_attributes})."
                )

        self.embedding = embedding
        self.force_unique_id = force_unique_id
        self.chunk_type = chunk_type

        if id is not None:
            self.id: str = str(id)
        else:
            self.id: str = self._get_id(id_hash_keys=id_hash_keys)

    def _get_id(self, id_hash_keys: list[str] | None = None):
        """
        Generate the id of a document by creating the hash of strings. By default the content of a document is
        used to generate the hash. There are two ways of modifying the generated id of a document. Either static keys
        or a selection of the content.
        :param id_hash_keys: Optional list of fields that should be dynamically used to generate the hash.
        """

        if id_hash_keys is None and not self.force_unique_id:
            return f"{mmh3.hash128(str(self.content), signed=False):02x}"
        elif id_hash_keys is None:
            return str(uuid.uuid4())

        final_hash_key = ""
        for attr in id_hash_keys:
            final_hash_key += ":" + str(getattr(self, attr))

        if final_hash_key == "":
            raise ValueError("Cant't create 'Document': 'id_hash_keys' must contain at least one of ['content', 'meta']")

        return f"{mmh3.hash128(final_hash_key, signed=False):02x}"

    def to_dict(self, field_map={}, uuid_to_str: bool = False) -> dict:  # noqa: B006
        inv_field_map = {v: k for k, v in field_map.items()}
        _doc: dict[str, str] = {}
        for k, v in self.__dict__.items():
            # Exclude internal fields (Pydantic, ...) fields from the conversion process
            if k.startswith("__"):
                continue
            if k == "content":  # noqa: SIM102
                if self.content_type == "table" and isinstance(self.content, pd.DataFrame):
                    v = [self.content.columns.tolist()] + self.content.values.tolist()
            k = k if k not in inv_field_map else inv_field_map[k]  # noqa: SIM401
            _doc[k] = v
        if uuid_to_str:
            return maybe_cast_to_str(_doc, uuid_to_str=True)
        return _doc

    @classmethod
    def from_dict(
        cls,
        dict: dict[str, Any],
        field_map: dict[str, Any] = {},  # noqa: B006
        id_hash_keys: list[str] | None = None,
        force_unique_id: bool = False,
        cast_meta_fields: list[str] | None = None,
    ):

        _doc = dict.copy()
        init_args = [
            "content",
            "content_type",
            "dataframe",
            "keywords",
            "id",
            "score",
            "meta",
            "embedding",
            "force_unique_id",
            "chunk_type",
        ]
        if "meta" not in _doc.keys():  # noqa: SIM118
            _doc["meta"] = {}
        # copy additional fields into "meta"
        for k, v in _doc.items():
            # Exclude internal fields (Pydantic, ...) fields from the conversion process
            if k.startswith("__"):
                continue
            if k not in init_args and k not in field_map:
                value = json.dumps(v, ensure_ascii=False) if cast_meta_fields is not None and k in cast_meta_fields else v
                _doc["meta"][k] = value
        # remove additional fields from top level
        _new_doc = {}
        for k, v in _doc.items():
            if k in init_args:
                _new_doc[k] = v
            elif k in field_map:
                k = field_map[k]
                _new_doc[k] = v

        if _doc.get("id") is None:
            _new_doc["id_hash_keys"] = id_hash_keys
            _new_doc["force_unique_id"] = force_unique_id

        # Convert list of rows to pd.DataFrame
        if _new_doc.get("content_type") == "table" and isinstance(_new_doc["content"], list):
            _new_doc["content"] = pd.DataFrame(columns=_new_doc["content"][0], data=_new_doc["content"][1:])

        return cls(**_new_doc)

    @classmethod
    def from_json(cls, data: str, field_map={}):  # noqa: B006
        d = json.loads(data)
        return cls.from_dict(d, field_map=field_map)

    def __eq__(self, other):
        return (
            isinstance(other, self.__class__)
            and getattr(other, "content", None) == self.content
            and getattr(other, "content_type", None) == self.content_type
            and getattr(other, "dataframe", None) == self.dataframe
            and getattr(other, "keywords", None) == self.keywords
            and getattr(other, "id", None) == self.id
            and getattr(other, "score", None) == self.score
            and getattr(other, "meta", None) == self.meta
            and np.array_equal(getattr(other, "embedding", None), self.embedding)  # type: ignore
        )

    def __repr__(self):
        doc_dict = self.to_dict()
        embedding = doc_dict.get("embedding", None)
        if embedding is not None:
            doc_dict["embedding"] = f"<embedding of shape {getattr(embedding, 'shape', '[no shape]')}>"
        return f"<Document: {str(doc_dict)}>"

    def __str__(self):
        # In some cases, self.content is None (therefore not subscriptable)
        if self.content is None:
            return f"<Document: id={self.id}, content=None>"
        return f"<Document: id={self.id}, content='{self.content[:100]}{'...' if len(self.content) > 100 else ''}'>"

    def __lt__(self, other):
        """Enable sorting of Documents by score"""
        return self.score < other.score


class Message(BaseModel):
    content: str


# Модель запроса для /is_done
class RenderIn(BaseModel):
    uuid: str


class TsRenderIn(BaseModel):
    uuid: str
    start_date: str
    end_date: str


# {"uuid":"991cff34-9071-4763-babf-3f00d985cb5a","start_date":"2025-09-02T16:05:07.486Z","end_date":"2025-10-02T16:05:07.486Z"}


class TsRenderOut(BaseModel):
    positives: list[int]
    negatives: list[int]
    neutrals: list[int]
    dates: list[int]
    uuid: str


# ---------- I/O models ----------
class ItemIn(BaseModel):
    id: int
    text: str


class PredictIn(BaseModel):
    data: Annotated[List[ItemIn], Field(min_items=1)]


class ItemOut(BaseModel):
    id: int
    topics: List[str]
    sentiments: List[str]


class PredictOut(BaseModel):
    predictions: List[ItemOut]
